<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="BepInEx.Core">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/core/BepInEx.Core.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/interop/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>

    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/core/BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>

    <Reference Include="BepInEx.Unity.Common">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/core/BepInEx.Unity.Common.dll</HintPath>
    </Reference>

    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/core/Il2CppInterop.Runtime.dll</HintPath>
    </Reference>

    <Reference Include="Il2Cppmscorlib">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/interop/Il2Cppmscorlib.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/interop/UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>/home/gfd/Documents/Games/Among Us/BepInEx/interop/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>

  </ItemGroup>

</Project>          
